### ISSUE TITLE
Don't work decompilation

### ISSUE THREAD

**Issue by fefemf10** [ShaneBeeStudios/McDeob#16]
Remapping was successful, but for some reason, decompilation does not start.
In the task manager, the load on the processor is 0%
Installed Java 17, from adoptium.
Screenshot https://imgur.com/CVm2V7f

**Comment by ShaneBeee** [comment]
FernFlower and Reconstruct repo have both been updated.
If you want to try your stuff again, go for it.
I had to move a few things around, do to how reconstruct updated, so you will have to fix a few things

**Comment by ShaneBeee** [comment]
closing as I believe this was fixed
