### ISSUE TITLE
package-info files are not decompiled correctly

### ISSUE THREAD

**Issue by DalekCraft2** [ShaneBeeStudios/McDeob#18]
Package info files are supposed to have annotations above the package line, and then imports, and then the file ends. However, the decompiled java files instead have the annotations above an `interface package-info {}` line, which does not compile anyway due to the `package` part of the interface's name being recognized as a keyword. Below is an example of what I mean.

Expected:

```java
@ParametersAreNonnullByDefault
package foo.bar;

import javax.annotation.ParametersAreNonnullByDefault;
```

Got:

```java
package foo.bar;

import javax.annotation.ParametersAreNonnullByDefault;

// $FF: synthetic class
@ParametersAreNonnullByDefault
interface package-info {
}
```

**Comment by ShaneBeee** [comment]
as with #22 I did not write the decompiler. Please see that issue if you wish to report issues with the decompiler.
