### ISSUE TITLE
Some classes become records

### ISSUE THREAD

**Issue by DalekCraft2** [ShaneBeeStudios/McDeob#19]
A lot of classes get turned into records for some reason, even if they have fields outside of the constructor's parameters. I think that it is because those classes' constructors all delegate to one specific constructor (or they only have one constructor), which is a requirement for records, so maybe the decompiler mistook those classes for records.

**Comment by ShaneBeee** [comment]
as with #22 I did not write the decompiler. Please see that issue if you wish to report issues with the decompiler.
