### ISSUE TITLE
Workspace and Recompiling

### ISSUE THREAD

**Issue by DaMotherYeeter** [ShaneBeeStudios/McDeob#2]
I need help as to where to point my workspace to and how I recompile 1.15.2 in either NetBeans or Eclipse. Below is the src folder that I created with the unzipped zip file
![image](https://user-images.githubusercontent.com/65098422/85075593-c0164480-b17b-11ea-9be3-3cb4ee3bfe48.png)

Sorry this is not an issue, but I did not understand and I thought this was the best way to get what I needed.
-DaMotherYeeter

**Comment by ShaneBeee** [comment]
You probably won't be able to recompile this.
The de-obfuscation processes misses some classes, and the decompilation process breaks some stuff.
This is purely for your own personal use. 

I wish that the output was buildable, but unfortunately the API im using the de-obfuscate breaks a lot of stuff.
