### ISSUE TITLE
Generics

### ISSUE THREAD

**Issue by DalekCraft2** [ShaneBeeStudios/McDeob#21]
I am fairly certain of that most decompilers do not include generics because most generics get reduced to `Object` when compiled. I have no idea of whether it is possible, but can this decompiler be made to infer generics from instance variable types, and from methods?

I refer to both method and class generics here, by the way.

**Comment by ShaneBeee** [comment]
as with #22 I did not write the decompiler. Please see that issue if you wish to report issues with the decompiler.
