### ISSUE TITLE
Cannot run an deobfuscated Minecraft Server jar file

### ISSUE THREAD

**Issue by Ranzeplay** [ShaneBeeStudios/McDeob#23]
I used McDeob v2.1.40 to deobfuscate the Minecraft Server 1.18.1, but when I tried to run it, I got this error message:
```
$> java -jar .\remapped_server-1.18.1.jar
Error: Unable to initialize main class net.minecraft.server.Main
Caused by: java.lang.NoClassDefFoundError: joptsimple/OptionSpec
```
Is the remapped server file broken?

**Comment by ShaneBeee** [comment]
As per the overview page on SpigotMC:
<img width="1532" alt="Screen Shot 2022-01-09 at 10 11 27 AM" src="https://user-images.githubusercontent.com/20008482/148694851-18966b8b-2f64-415c-afe2-bed66c1a8d47.png">

Some classes are missed, as well I think all of the external libraries Minecraft adds are also skipped. 
This app basically just deopfuscates and decompiles Minecraft to see the code, but not actually use it.

**Comment by Ranzeplay** [comment]
Thank you very much!
