### ISSUE TITLE
Broken interface on Ubuntu

### ISSUE THREAD

**Issue by TobiasDeBruijn** [ShaneBeeStudios/McDeob#25]
See screenshot:
![image](https://user-images.githubusercontent.com/28569170/158216296-8f6841ae-c61e-4d16-b072-9192d2ba7e16.png)

Running Ubuntu 20 with OpenJDK 17 from `openjdk-17-jdk`, running latest McDeob

**Comment by ShaneBeee** [comment]
I forgot to reply to this.
Since I don't have Linux, I won't be able to test this, and try to fix it. 
I will leave this here in hopes someone who uses Linux sees this, and could potentially do a PR to fix

**Comment by ShaneBeee** [comment]
fixed in McDeob 2.2.0
