### ISSUE TITLE
Add save progress

### ISSUE THREAD

**Issue by fefemf10** [ShaneBeeStudios/McDeob#26]
Add the ability to pause/resume and save progress, as well as automatically save progress every 5-10 minutes

**Comment by ShaneBeee** [comment]
due to the fact that I didnt write the remapper, nor the decompiler, I wouldn't be able to do that

on top of that, I dont think this program takes really all that long, that a progress saver would really be needed

**Comment by ShaneBeee** [comment]
closing this due to what I said before:


> due to the fact that I didnt write the remapper, nor the decompiler, I wouldn't be able to do that
