### ISSUE TITLE
MacOS Archive error.

### ISSUE THREAD

**Issue by nik-1x** [ShaneBeeStudios/McDeob#28]
When i was decompiled server sources (1.19), i go to **~/McDeob/final-decompile/remapped_server_1.19.zip** and try to unzip.
Default MacOS unzip tool says NO. (This format is not supported error)

**Comment by ShaneBeee** [comment]
I've had this happen with many different zip files.
macOS' default unzipped is awful.
I recommend using [**The Unarchiver**](https://theunarchiver.com) ... it's what I use, works great. 
I will mark this as a bug, but I can not guarantee I'll fix it anytime soon, as I'm not really sure how.
Gonna have to do some googling I guess.

**Comment by ShaneBeee** [comment]
im going to close this as I see now easy way to resolve it.
