### ISSUE TITLE
I cannot start the program

### ISSUE THREAD

**Issue by Nexereczeq** [ShaneBeeStudios/McDeob#29]
Can you help?
Pops up
Error: A JNI error has occurred, check the installation and try again
A Java exception has occurred 
  I use windows

**Comment by ShaneBeee** [comment]
I don't have windows, so I can't really test.
But there's not much info here for me to go on to really provide any help

**Comment by bluelhf** [comment]
@Nexereczeq Have you tried opening Command Prompt and launching it from there?

**Comment by ShaneBeee** [comment]
closing due to lack of info and no response
