### ISSUE TITLE
[Linux] Bug when remapping/decompiling both client and server

### ISSUE THREAD

**Issue by BenCat07** [ShaneBeeStudios/McDeob#3]
Not sure if this is linux only, but if you decompile/remap client first, and then try to do server aswell without restarting the program, it doesn't remap/decompile the server, it just downloads the jar and assumes it is done.

**Comment by BenCat07** [comment]
i assume this happens because some variables do not get reset on hitting the button

**Comment by ShaneBeee** [comment]
> i assume this happens because some variables do not get reset on hitting the button

Thats probably a safe bet. I most likely made the assumption a user was not going to run the app twice.
Ill doing some testing tomorrow, and if I find the issue I will fix it up.

**Comment by BenCat07** [comment]
Thanks for the quick reply, currently using your program to figure out how firework damage is calculated exactly :P

**Comment by ShaneBeee** [comment]
Ok I did some testing, and I can confirm, when going from client -> server, it just stops after downloading

<img width="612" alt="Screen Shot 2020-12-17 at 1 42 19 PM" src="https://user-images.githubusercontent.com/20008482/102547231-c2475600-406d-11eb-9c3d-280086422bc2.png">

I will do my best to get this bug sorted out.

**Comment by ShaneBeee** [comment]
Ok, so turns out the issue was with the remapper I am using (Reconstruct), it has a static list of Transformers, which has no way of clearing, so if the program is run more than once, it failed to re-register the transformer.

I have a fork of Reconstruct (because I had to change the logger), so I just added a method to clear the transformers.

**Comment by ShaneBeee** [comment]
Ok, fixed and released:
https://github.com/ShaneBeeStudios/McDeob/releases/tag/2.1.24
