### ISSUE TITLE
Stuck on Decompilation (1.17.1)

### ISSUE THREAD

**Issue by BenCat07** [ShaneBeeStudios/McDeob#33]
This has never happened to me before, but it happens now, so i am here to report it... i am unsure if it is the right place though, i might need to report it at the decompilation programs tracker (except i forgot its name)

Decompiling 1.17.1 Server Jar results in it Locking up after 
```
INFO:  ... done
INFO:  Decompiling class org/apache/logging/log4j/util/StackLocator
```

This is consistent and has happened 3/3 attempts, and only seems to happen on 1.17.1 Server decompile, client works fine.
CPU usage is not going down, and memory usage seems to very slowly creep up.
Some extra info about my java version:
```
openjdk 17.0.4.1 2022-08-12
OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)

```

Thanks for making this by the way, i often use it in order to check Minecraft's code, e.g. Ore Spreads, Mining Speeds, How Enchantments work at higher than vanilla levels, etc.

**Comment by BenCat07** [comment]
passing "mpm" to fernflower with a duration would not fix the issue, but at least sort of avoid it

**Comment by BenCat07** [comment]
Debugging by using Fernflower directly instead of the curseforge download of your project... Maybe it just needs an update, we'll see...

**Comment by BenCat07** [comment]
Confirmed it, newer versions of fernflower work fine, spigotMC download needs to be updated, or this repo (not sure if the code on this rpeo is up-to-date enough)

**Comment by ShaneBeee** [comment]
closing as I could never replicate this.
