### ISSUE TITLE
Decompilation unexcepted output

### ISSUE THREAD

**Issue by N4TH4NOT** [ShaneBeeStudios/McDeob#34]
For a while, the server jar no longer contains classes, it now contains multiple jar file, the "real" server jar is one of those.

So as a result, il is not affected by the decompilation process and remapping process.

**Comment by ShaneBeee** [comment]
I'm not exactly sure what you are talking about. 
Your issue is not very clear. 
The Minecraft server jar is remapped and decompiled.
