### ISSUE TITLE
Please add Location for output file Path to Document

### ISSUE THREAD

**Issue by ahmadronaghdev** [ShaneBeeStudios/McDeob#37]
Hi Thanks a lot for the Tools you developed
please mention the output file path in Documentation I search in code for it finally i found it in final-decompile folder in User folder. 

Thanks a lot

**Comment by ShaneBeee** [comment]
just to double check, which OS are you using?

**Comment by ahmadronaghdev** [comment]
I use mac os

**Comment by ShaneBeee** [comment]
I could have sworn I had it in the wiki, ill update now, thank you!
