### ISSUE TITLE
Where does the files end up on macOS?

### ISSUE THREAD

**Issue by mfnalex** [ShaneBeeStudios/McDeob#42]
Weird question, but I extracted the executable from the DMG into a new folder and ran it there, and it completed fine, but where are the files now? The folder where I ran it from is still empty :')

<img width="612" alt="Bildschirmfoto 2024-02-25 um 02 11 07" src="https://github.com/ShaneBeeStudios/McDeob/assets/1122571/ffa6bab4-2247-4d35-85b0-6b7fc01de3e5">
<img width="1032" alt="Bildschirmfoto 2024-02-25 um 02 11 13" src="https://github.com/ShaneBeeStudios/McDeob/assets/1122571/c392b4b8-8911-45a4-9f79-e7abe8b37873">

**Comment by ShaneBeee** [comment]
https://github.com/ShaneBeeStudios/McDeob/wiki/macOS#output-files

**Comment by mfnalex** [comment]
Thanks!

**Comment by ShaneBeee** [comment]
you're welcome :)
