### ISSUE TITLE
Can't decompile pre-releases

### ISSUE THREAD

**Issue by Jiingy** [ShaneBeeStudios/McDeob#44]
Can only decompile snapshots, and full releases, not pre-releases. This also presumably affects release candidates.
![image](https://github.com/ShaneBeeStudios/McDeob/assets/69827559/0276f13a-ec35-47a6-8ec9-3f3e4fd9f17f)
![image](https://github.com/ShaneBeeStudios/McDeob/assets/69827559/82d8f97b-dcda-4799-903d-faf6fb7e8408)

**Comment by ShaneBeee** [comment]
They're in numerical order, so the pre's are pushed down
<img width="498" alt="Screenshot 2024-04-16 at 8 41 31 PM" src="https://github.com/ShaneBeeStudios/McDeob/assets/20008482/e3c88d96-94ea-40f6-8b52-f1aa4a304784">

**Comment by ShaneBeee** [comment]
I did a small change in the code so next release the versions will be in order of release date rather than sorting alphabetically

**Comment by Jiingy** [comment]
That you for the clarification, apologies for not checking first about the sort order

**Comment by ShaneBeee** [comment]
thats fine, the order was kinda stupid.
But the new version will be much nicer.

**Comment by ShaneBeee** [comment]
closing as "fixed" (but not fixed, just changed, you get me)
