### ISSUE TITLE
A Java Exception has occurred.

### ISSUE THREAD

**Issue by JakeGBLP** [ShaneBeeStudios/McDeob#48]
![image](https://github.com/user-attachments/assets/deb00e36-1895-4c2b-88b4-aaa22a4fccfe)

This is all I have

**Comment by ShaneBeee** [comment]
Looks like an incorrect java version was used.
Can you please run it from console and show what the console spits out.

**Comment by JakeGBLP** [comment]
Running it from the Command Prompt worked, not sure why...

**Comment by ShaneBeee** [comment]
Ive seen this happen before where it was just an older java version being used for some reason.
