### ISSUE TITLE
Decompile option selected, but returns .jar file. Any help?

### ISSUE THREAD

**Issue by SwingCSS** [ShaneBeeStudios/McDeob#6]
I'm on Mac OS X Catalina 101.5.4, and the returned files were solely .jar,

**Comment by ShaneBeee** [comment]
<img width="1001" alt="Screen Shot 2020-12-20 at 6 01 52 PM" src="https://user-images.githubusercontent.com/20008482/102731758-8a4e4600-42ed-11eb-90dd-b59cbfabd0f3.png">

**Comment by SwingCSS** [comment]
I' attempted to unzip the jar file earlier, but I just get a duplicate of the original .jar file. I'm using the default Archive Utility, should I use a third-party software?

**Comment by ShaneBeee** [comment]
Im not sure, I've only ever used "The Unarchiver"

**Comment by SwingCSS** [comment]
Ah. I'll try that, hopefully it'll work.

**Comment by SwingCSS** [comment]
Yeah. The default utility extracts it into a CPGZ file, while The Unarchiver will extract the sources.
